spin_version = "1"
authors = ["Bojanche Stojchevski <bojanche@propel.us>"]
description = "C2~challenge nr. 2 AoS"
name = "aos-c2-rust"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "aos-c2-rust"
source = "target/wasm32-wasi/release/aos_c2_rust.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
