spin_version = "1"
authors = ["Bojanche Stojchevski <bojanche@propel.us>"]
description = ""
name = "aos-c1-go"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "aos-c1-go"
source = "main.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
