spin_version = "1"
authors = ["Bojanche Stojchevski <bojanche@propel.us>"]
description = ""
name = "aos-c2-rust-hello"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "aos-c2-rust-hello"
source = "target/wasm32-wasi/release/aos_c2_rust_hello.wasm"
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
